<?php


namespace TodoList;

use \TodoList\Model\Todo;
use \TodoList\Util\Utils;

//~ Template for index.php
// variables:
//  $template - page to be displayed (included)
//  $flashes - flash messages

?>
<!DOCTYPE html>
<html>
<head>
    <title>Application Company's List</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" >
    <meta name="description" content="TODO List - sample application for NetBeans IDE" >
    <meta name="keywords" content="NetBeans, PHP" >
    <meta name="author" content="NetBeans PHP team" >

    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/redmond/jquery-ui.css" >
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" >
    <link href="css/style.css" rel="stylesheet" type="text/css" >
    <link href="css/layout.css" rel="stylesheet" type="text/css" >

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
    <script type="text/javascript" src="js/script.js"></script>

</head>
<body id="page">
    <div class="tail-top-right"></div>
    <div id="main">
        <!-- header -->
        <div id="header">
            <i class="material-icons logo">assignment</i>
            <div class="title">
                <h1>APPLICATION Company's List</h1>
                <h2>a simple PHP Application</h2>
            </div>
            <div class="nb">
                <h3>developed with</h3>
                <a href="https://netbeans.org/features/php/" target="_blank" title="developed with NetBeans PHP"><img src="img/NB-IDE-logo.png" alt="NetBeans logo"></a>
            </div>
        </div>     
        <!-- content   -->
        <div id="content">
            <div class="wrapper">
                <div class="col-1">
                    <div class="box">
                        <div class="inner">
                            <ul class="list">
                                <li><span><a href="<?php echo Utils::createLink('home'); ?>">Home</a></span></li>
                                <li><span><a href="<?php echo Utils::createLink('list', ['status' => Todo::STATUS_PENDING]); ?>" title="Pending Companies"
                                             ><?php echo Utils::iconStatus(Todo::STATUS_PENDING); ?>Pending Companies</a></span></li>
                                <li><span><a href="<?php echo Utils::createLink('list', ['status' => Todo::STATUS_DONE]); ?>" title="Done Companies"
                                             ><?php echo Utils::iconStatus(Todo::STATUS_DONE); ?>Done Companies</a></span></li>
                                <li><span><a href="<?php echo Utils::createLink('list', ['status' => Todo::STATUS_VOIDED]); ?>" title="Voided Companies"
                                             ><?php echo Utils::iconStatus(Todo::STATUS_VOIDED); ?>Voided Companies</a></span></li>
                                <li><span><a href="<?php echo Utils::createLink('add-edit'); ?>" title="Add Company"
                                             ><i class="material-icons new">insert_invitation</i>Add Company</a></span></li>
                                <li class="last"><span><a href="<?php echo Utils::createLink('undelete'); ?>" title="Undelete Company"
                                             ><i class="material-icons new">delete</i>Undelete Company</a></span></li>
                                <?php if ( $_SESSION['credentialsValid']): ?>             
                                    <li><span><a href="<?php echo Utils::createLink('homeLogout'); ?>">Logout</a></span></li>
                                <?php endif; ?>    
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="indent">
                        <?php if ($flashes): ?>
                            <ul id="flashes">
                            <?php foreach ($flashes as $flash): ?>
                                <li><?php echo $flash; ?></li>
                            <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php require $template; ?> 
                    </div>
                </div>
            </div>
        </div>
        <!-- footer -->
        <div id="footer">
            <div class="indent">
                <div class="fleft"><a href="http://www.duenda.freeoda.com/" target=_blank >Calix space developer team</a>, 2018 &copy; Copyright Calix corp., All rights reserved</div>
            </div>
        </div>
    </div>
</body>
</html>
