<?php


namespace TodoList;

use \TodoList\Model\Todo;
use \TodoList\Util\Utils;
use \TodoList\Validation\ValidationError;

//~ Template for add-edit.php
// variables:
//  $errors - validation errors
//  $todo - submitted TODO
//  $edit - true for EDIT, false for ADD

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error ValidationError */
        if ($error->getSource() == $title) {
            return ' error-field';
        }
    }
    return '';
}

/* @var $todo Todo */
?>

<h1>
    <?php if ($edit): ?>
        <?php echo Utils::escape($todo->getCompany()); ?>
    <?php else: ?>
        <i class="material-icons new">insert_invitation</i>
        Add new TODO
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error ValidationError */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<form action="#" method="post"  method="get">
    <fieldset>
        <div class="field">
            <label>Title:</label>
             <input type="text" name="todo[title]" value="<?php echo Utils::escape($todo->getTitle()); ?>"
                   class="text<?php echo error_field('title', $errors); ?>"/>
        </div>

        <div class="field">
        <label>Prename:</label>
            <input type="text" name="todo[pre_name]" value="<?php echo Utils::escape($todo->getPre_name()); ?>"
                   class="text<?php echo error_field('pre_name', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Name:</label>
            <input type="text" name="todo[name]" value="<?php echo Utils::escape($todo->getName()); ?>"
                   class="text<?php echo error_field('name', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Company:</label>
            <input type="text" name="todo[company]" value="<?php echo Utils::escape($todo->getCompany()); ?>"
                   class="text<?php echo error_field('company', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Address:</label>
            <input type="text" name="todo[address]" value="<?php echo Utils::escape($todo->getAddress()); ?>"
                   class="text<?php echo error_field('address', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Zip city:</label>
            <input type="text" name="todo[zip_city]" value="<?php echo Utils::escape($todo->getZip_city()); ?>"
                   class="text<?php echo error_field('zip_city', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Greetingline:</label>
            <input type="text" name="todo[greeting_line]" value="<?php echo Utils::escape($todo->getGreeting_line()); ?>"
                   class="text<?php echo error_field('greeting_line', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Emailaddress:</label>
            <input type="text" name="todo[email]" value="<?php echo Utils::escape($todo->getEmail()); ?>"
                   class="text<?php echo error_field('email', $errors); ?>"/>
        </div>
        <div class="field">
            <label>Homepage:</label>
            <input type="text" name="todo[homepage]" value="<?php echo Utils::escape($todo->getHomepage()); ?>"
                   class="text<?php echo error_field('homepage', $errors); ?>"/>
        </div>          
        <div class="field">
        <label>Business:</label>
            <textarea name="todo[business]" cols="1" rows="1"
                      class="<?php echo error_field('business', $errors); ?>"><?php echo Utils::escape($todo->getBusiness()); ?></textarea>
        </div>
        <div class="field">
            <label>Priority:</label>
            <select name="todo[priority]">
            <?php foreach (Todo::allPriorities() as $priority): ?>
                <option value="<?php echo $priority; ?>"
                        <?php if ($priority == $todo->getPriority()): ?>
                            selected="selected"
                        <?php endif; ?>
                        ><?php echo $priority; ?></option>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
        <label>Comment:</label>
            <textarea name="todo[comment]" cols="1" rows="1"
                      class="<?php echo error_field('comment', $errors); ?>"><?php echo Utils::escape($todo->getComment()); ?></textarea>
        </div>
         <div class="field">
            <label>date added:</label>
            <input type="text" name="todo[dateAdded_date]" value="<?php echo Utils::escape($todo->getDateAdded()->format('Y-n-j')); ?>"
                   class="text datepicker<?php echo error_field('dateAdded_date', $errors); ?>" />
            &nbsp;
            <select name="todo[dateAdded_hour]">
            <?php for ($i = 0; $i < 24; ++$i): ?>
                <?php $hour = str_pad($i, 2, '0', STR_PAD_LEFT); ?>
                <option value="<?php echo $hour; ?>"
                        <?php if ($todo->getDateAdded()
                                && ($hour == $todo->getDateAdded()->format('H'))): ?>
                            selected="selected"
                        <?php endif; ?>
                        ><?php echo $hour; ?></option>
            <?php endfor; ?>
            </select>
            :
            <select name="todo[dateAdded_minute]">
            <?php for ($i = 0; $i < 60; $i = $i + 15): ?>
                <?php $minute = str_pad($i, 2, '0', STR_PAD_LEFT); ?>
                <option value="<?php echo $minute; ?>"
                        <?php if ($todo->getDateAdded()
                                && $minute == $todo->getDateAdded()->format('i')): ?>
                            selected="selected"
                        <?php endif; ?>
                        ><?php echo $minute; ?></option>
            <?php endfor; ?>
            </select>
        </div>
        <div class="wrapper">
            <input type="submit" name="cancel" value="CANCEL" class="submit" />
            <input type="submit" name="save" value="<?php echo $edit ? 'SAVE' : 'ADD'; ?>" class="submit" />
        </div>
    </fieldset>
</form>
