<?php


namespace TodoList;

use \TodoList\Model\Todo;
use \TodoList\Util\Utils;

//~ Template for detail.php
// variables:
//  $todo - TODO to be displayed
//  $tooLate - if the task should have been done already

/* @var $todo Todo */
?>

<table class="detail">
    <tr>       
        <th>Company</th>
        <td><?php echo Utils::escape($todo->getCompany()); echo ", "; echo Utils::escape($todo->getZip_city()); echo Utils::iconPriority($todo->getPriority()); ?></td>
    </tr>
    <tr>
        <th>Business</th>
        <td><?php echo Utils::escape($todo->getBusiness()); ?></td>
    </tr>

    <tr>
        <th>date added</th>
        <td><?php echo Utils::escape(Utils::formatDateTime($todo->getDateAdded())); ?></td>
    </tr>
    <tr>
        <th>Comment</th>
        <td><?php echo Utils::escape($todo->getComment()); ?></td>
    </tr>
    <tr>
        <th>Status</th>
        <td><?php echo Utils::iconStatus($todo->getStatus()); ?></td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <th></th>
        <td>
            <div class="statuses">
            <?php foreach (Todo::allStatuses() as $status): ?>
                <?php if ($status != $todo->getStatus()): ?>
                    <a href="<?php echo Utils::createLink('change-status', ['id' => $todo->getId(), 'status' => $status]); ?>" title="Change TODO status to <?php echo Utils::capitalize($status); ?>."
                       class="change-status-link" title="Make it <?php echo Utils::capitalize($status); ?>"
                       ><?php echo Utils::iconStatus($status, false, false); ?></a>
                <?php else: ?>
                    <span title="This TODO is already <?php echo Utils::capitalize($status); ?>.">
                        <?php echo Utils::iconStatus($status, true, false); ?>
                    </span>
                <?php endif; ?>
            <?php endforeach; ?>
            </div>
            <div class="actions">
                <a href="<?php echo Utils::createLink('add-edit', ['id' => $todo->getId()]); ?>" title="Edit it."><i class="material-icons multi">edit</i></a>
                <a href="<?php echo Utils::createLink('getcsv', ['id' => $todo->getId()]); ?>" title="Download it as CSV-file"><i class="material-icons multi">arrow_downward</i></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <a href="<?php echo Utils::createLink('list', ['status' => $todo->getStatus()]); ?>" title="Back to the list."
       ><i class="material-icons">fast_rewind</i>To the list</a>
</p>

<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comment:</label>
                <textarea name="comment" cols="3" rows="2"><?php echo Utils::escape($todo->getComment()); ?></textarea>
            </div>
        </fieldset>
    </form>
</div>