<?php

namespace TodoList;
?>
<h1>Welcome!</h1> 
<!--   within this page build, check for $session->credentialsValid and add user/pwd fields if needed   --> 
<?php if ( !$_SESSION['credentialsValid']): ?>
    <form action="index.php" method="post">
        <p class = "p"><b>please enter valid username and password</b>  </p>
        <p>    
            username: <input type="text" name="username" value="<?php echo $_SESSION['username'] ?>" />
        </p>
        &nbsp;
        <p>    
            password: <input type="password" name="password" value="<?php echo $_SESSION['password'] ?>" />
        </p>
        <input type="submit" value="Submit" class="paddingButton  smallTopMargin">
    </form>
    &nbsp;
<?php endif; ?>
<p class="p   smallTopMargin">Welcome to PHP IDE sample - <b>APPLY Company's List application</b>.</p>
<ul class="p">
    This sample does not use any PHP framework, it will show you possibilities how to:
    <li>prevent public access to your scripts</li>
    <li>config your application</li>
    <li>access your database data</li>
    <li>change your database data (with redirect-after-post pattern)</li>
    <li>validate your data</li>
    <li>split scripts and templates</li>
    <li>handle expected and unexpected exceptions</li>
    <li>server uses php version 7.2.2, fixes tobe tested...</li>
</ul>
<p class="p"><b>This sample is not intented to be used on a production server without any changes.</b></p>
