<?php


namespace TodoList;

?>
<h1>Welcome!</h1> 
<!--   within this page build, check for $session->credentialsValid and add user/pwd fields if needed   --> 
<?php if ($_SESSION['credentialsValid']== 0): ?>
<p class = "p"><b>please enter valid username and password</b>  </p>
<p>    
        username: <input type="text" name="username" value="<?php echo $_SESSION['username'] ?>" />
</p>
&nbsp;
<p>    
        password: <input type="password" name="password" value="<?php echo $_SESSION['password'] ?>" />
</p>
&nbsp;
<?php endif; ?>
<p class="p">Welcome to the NetBeans PHP IDE sample - <b>TODO List application</b>.</p>
<ul class="p">
    This sample does not use any PHP framework, it will show you possibilities how to:
    <li>prevent public access to your scripts</li>
    <li>config your application</li>
    <li>access your database data</li>
    <li>change your database data (with redirect-after-post pattern)</li>
    <li>validate your data</li>
    <li>split scripts and templates</li>
    <li>handle expected and unexpected exceptions</li>
</ul>
<p class="p">Detailed information can be found in the <i>readme.html</i> file (in project directory).</p>
<p class="p"><b>This sample is not intented to be used on a production server without any changes.</b></p>
