<?php


namespace TodoList;

use \DateTime;
use \TodoList\Model\Todo;
use \TodoList\Util\Utils;

//~ Template for list.php
// variables:
//  $title - page title
//  $status - status of TODOs to be displayed
//  $todos - TODOs to be displayed

?>
<div class="titleBox">
<h1>
    <?php echo Utils::iconStatus($status); ?>
    <?php echo " ".$amtTodos." "; ?>
    <?php echo $title; ?>
</h1>
</div>
 <div  class="sortingBox">
        <form action="index.php?page=list&status=<?php echo $status ?>" method="post" class="fRight">  
            <fieldset  >
                <legend>&nbsp;list sorting&nbsp;</legend>
                <div class="wrapper">
                    <table>
                        <tr>
                            <td>  <input type="submit" name="companySortButton" value="company" class="submit" />  </td>
                            <td> <input type="submit" name="dateAddedSortButton" value="date added" class="submit" />  </td>
                        </tr>    
                        <tr>
                            <td class= aligncenter> <i class="material-icons multi">arrow_downward</i>  </td>
                            <td class= aligncenter> <i class="material-icons multi">arrow_upward</i>  </td>
                        </tr>
                    </table>
                </div>    
            </fieldset>
              
        </form>
      </div>  
<?php if (empty($todos)): ?>
    <p>No TODO items found.</p>
<?php else: ?>
    <ul class="list">
        <?php foreach ($todos as $todo): ?>
            <li>
                <h3>
                    <a href="<?php echo Utils::createLink('detail', ['id' => $todo->getId()]) ?>"><?php echo Utils::escape($todo->getCompany()); echo ", "; echo Utils::escape($todo->getZip_city()); ?></a>
                    <?php echo Utils::iconPriority($todo->getPriority()); ?>
                </h3>
                <?php if ($todo->getBusiness()): ?>
                    <p class="description"><?php echo Utils::escape($todo->getBusiness()); ?></p>
                <?php endif; ?>
                <p><span class="label">date added:</span> <?php echo Utils::escape(Utils::formatDateTime($todo->getDateAdded())); ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
