<?php


namespace TodoList;

use \DateTime;
use \TodoList\Model\Todo;
use \TodoList\Util\Utils;

//~ Template for list.php
// variables:
//  $title - page title
//  $status - status of TODOs to be displayed
//  $todos - TODOs to be displayed

?>

<h1>
    <?php echo Utils::iconStatus($status); ?>
    <?php echo " ".$amtTodos." "; ?>
    <?php echo $title; ?>
</h1>

<?php if (empty($todos)): ?>
    <p>No TODO items found.</p>
<?php else: ?>
    <ul class="list">
        <?php foreach ($todos as $todo): ?>
            <li>
                <h3>
                    <a href="<?php echo Utils::createLink('detail', ['id' => $todo->getId()]) ?>"><?php echo Utils::escape($todo->getCompany()); echo ", "; echo Utils::escape($todo->getZip_city()); ?></a>
                    <?php echo Utils::iconPriority($todo->getPriority()); ?>
                </h3>
                <?php if ($todo->getBusiness()): ?>
                    <p class="description"><?php echo Utils::escape($todo->getBusiness()); ?></p>
                <?php endif; ?>
                <p><span class="label">date added:</span> <?php echo Utils::escape(Utils::formatDateTime($todo->getDateAdded())); ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
